import { forwardRef } from 'react';
import { ShieldCheck } from 'lucide-react';
import MonthlyTrendChart from '../charts/MonthlyTrendChart';
import { formatDate, formatDateTime } from '../../utils/formatDate';
import './PrintableMonthlyReport.css';

const PrintableMonthlyReport = forwardRef(function PrintableMonthlyReport(
  { data, month, year, generatedBy },
  ref
) {
  if (!data) return null;

  const { summary = {}, chartData = [], incidents = [] } = data;
  const byStatus = summary.byStatus || {};
  const bySeverity = summary.bySeverity || {};
  const byCategory = summary.byCategory || {};
  const openIncidents = (byStatus.Open || 0) + (byStatus['Under Investigation'] || 0) + (byStatus.Assigned || 0);
  const resolvedIncidents = (byStatus.Resolved || 0) + (byStatus.Closed || 0);
  const reportingMonth = new Date(Number(year), Number(month) - 1).toLocaleString('default', { month: 'long' });
  const trendData = chartData.map((item) => ({ _id: `Day ${item.day}`, count: item.count }));

  const summaryItems = [
    ['Total Incidents', summary.total || 0],
    ['Open Incidents', openIncidents],
    ['Resolved Incidents', resolvedIncidents],
    ['High Risk Incidents', summary.highRiskCount || 0],
    ['Critical Incidents', bySeverity.Critical || 0],
  ];

  const renderDistribution = (title, values) => (
    <section className="print-report-section">
      <h2>{title}</h2>
      <div className="print-distribution-grid">
        {Object.keys(values).length > 0 ? Object.entries(values).map(([label, value]) => (
          <div className="print-distribution-item" key={label}>
            <span>{label}</span>
            <strong>{value}</strong>
          </div>
        )) : <p className="print-empty">No data available for this period.</p>}
      </div>
    </section>
  );

  return (
    <article ref={ref} className="print-report-source">
      <header className="print-report-header">
        <div className="print-brand-lockup">
          <span className="print-brand-mark"><ShieldCheck aria-hidden="true" /></span>
          <div>
            <p className="print-brand">SafeGuard AI</p>
            <p className="print-product">AI-Powered Safety Incident Management System</p>
          </div>
        </div>
        <div className="print-report-heading">
          <h1>Monthly Safety Incident Report</h1>
          <dl>
            <div><dt>Reporting Period</dt><dd>{reportingMonth} {year}</dd></div>
            <div><dt>Generated</dt><dd>{formatDateTime(new Date())}</dd></div>
            <div><dt>Generated By</dt><dd>{generatedBy || 'SafeGuard AI User'}</dd></div>
          </dl>
        </div>
      </header>

      <section className="print-report-section">
        <h2>Executive Summary</h2>
        <div className="print-summary-grid">
          {summaryItems.map(([label, value]) => (
            <div className="print-summary-item" key={label}>
              <strong>{value}</strong>
              <span>{label}</span>
            </div>
          ))}
        </div>
      </section>

      {renderDistribution('Severity Distribution', bySeverity)}
      {renderDistribution('Category Distribution', byCategory)}
      {renderDistribution('Status Distribution', byStatus)}

      <section className="print-report-section print-chart-section">
        <h2>Monthly Trend</h2>
        <MonthlyTrendChart data={trendData} />
      </section>

      <section className="print-report-section print-table-section">
        <h2>Incident Details</h2>
        {incidents.length > 0 ? (
          <table className="print-incident-table">
            <thead>
              <tr>
                <th>Incident ID</th><th>Title</th><th>Department</th><th>Severity</th><th>Status</th><th>Date Reported</th>
              </tr>
            </thead>
            <tbody>
              {incidents.map((incident) => (
                <tr key={incident._id}>
                  <td>{incident._id?.slice(-8).toUpperCase()}</td>
                  <td>{incident.title}</td>
                  <td>{incident.department?.name || '—'}</td>
                  <td>{incident.aiAnalysis?.severityLevel || '—'}</td>
                  <td>{incident.status}</td>
                  <td>{formatDate(incident.createdAt)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        ) : <p className="print-empty">No incidents were reported during this period.</p>}
      </section>

      <footer className="print-report-footer">
        <span>Generated by SafeGuard AI</span>
        <span>Confidential – Internal Safety Report</span>
        <span className="print-page-number" aria-label="Page number" />
      </footer>
    </article>
  );
});

export default PrintableMonthlyReport;
